---
title: "Making Reproducible Research Simple using RMarkdown and the OSF"
author-inputfile: "authors.tex" 
abstract: |
  The replication crisis has further eroded the public's trust in science. Many famous studies, even published in renowed journals, fail to produce the same results when replicated by other researchers. While this is the outcome of several problems in research, one aspect has gotten critical attention---reproducibility. The term reproducible research refers to studies that contain all materials necessary to reproduce the scientific results by other researchers. This allows others to identify flaws in calculations and improve scientific rigor. In this paper, we show a workflow for reproducible research using the R language and a set of additional packages and tools that simplify a reproducible research procedure.   
keywords: "Reproducible Research \\and Replication Crisis \\and Literate Programming."
bibliography: ["../bib/rpackages.bib", "../bib/bibliography.bib"]
biblio-style: "apalike"
link-citations: true
always_allow_html: true
output:
  bookdown::pdf_document2:
    fig_caption: true
    keep_tex: true
    template: lncs-template.tex
    md_extensions: +footnotes
    citation_package: biblatex
    dev: pdf
    
---


```{r knitr_init, echo = FALSE, message = FALSE, warning = FALSE, cache = FALSE, paged.print = TRUE}
## Global options
library(knitr)
#options(max.print = "75")
opts_chunk$set(echo = FALSE,
	             cache = FALSE,
               prompt = FALSE,
               tidy = TRUE,
               comment = NA,
               message = FALSE,
               warning = FALSE,
               out.width = '100%'
               )
opts_knit$set(width = 100)

# Load required libraries
library(rmdformats)
library(rmdtemplates)
library(tidyverse)
library(cowplot)
library(osfr)
# add libraries here

# Add libraries to cite here:
# I am using the bib folder version
pkgs <- c("knitr", "tidyverse", "rmdformats", "kableExtra", "scales", "psych", "rmdtemplates", "sdcMicro", "webshot", "here", "DiagrammeR", "citr", "drake", "esquisse", "usethis", "gramr", "questionr", "ggstatsplot")
#rmdtemplates::write_bib(pkgs)
```

```{r osf, echo = FALSE}
osf_GUID <- "kcbj5"
```



```{r child = '../rmds/10_introduction.Rmd'}
```

```{r child = '../rmds/20_research_compendium.Rmd'}
```

```{r child = '../rmds/30_open.Rmd'}
```

```{r child = '../rmds/40_drake.Rmd'}
```

```{r child = '../rmds/50_procedure.Rmd', eval = TRUE}
```

```{r child = '../rmds/60_discussion.Rmd', eval = TRUE}
```



# Acknowledgements {-}
This research was supported by the Digital Society research program funded by the Ministry of Culture and Science of the German State of North Rhine-Westphalia.
We would further like to thank the authors of the packages we have used.
```{r r_citations, eval = TRUE, include = TRUE, results = "asis"}
rmdtemplates::line_cite(pkgs) # This creates a single line citing all packages
#rmdtemplates::list_cite(pkgs) # This creates a "thightlist" of all packages 
```

# References
